version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: boardgames-db
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: boardgamesDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: